//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewscape.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ViewscapeTable
    {
        public int Id { get; set; }

        [StringLength(50, MinimumLength = 2)]
        [Required]
        public string Name { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required]
        public string City { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required]
        public string Country { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public Nullable<int> Cost { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public Nullable<int> Height { get; set; }

        [StringLength(50, MinimumLength = 2)]
        public string Style { get; set; }

        [StringLength(50, MinimumLength = 2)]
        public string Material { get; set; }
        public string Architect { get; set; }
        public int Completed { get; set; }

        [StringLength(5000, MinimumLength = 2)]
        [Required]
        public string Description { get; set; }

        [StringLength(5000, MinimumLength = 2)]
        public string Description2 { get; set; }

        [StringLength(5000, MinimumLength = 2)]
        public string Picture { get; set; }

        [StringLength(50, MinimumLength = 2)]
        [Required]
        public string UserFirstName { get; set; }

        [StringLength(50, MinimumLength = 2)]
        [Required]
        public string UserLastName { get; set; }
    }
}
